---
- name: Service sshd is enabled and started
  service:
    name: sshd
    enabled: yes
    state: started

- name: Service firewalld is disabled and stopped
  service:
    name: firewalld
    enabled: no
    state: stopped

- name: Increase inotify watchers
  sysctl:
    name: fs.inotify.max_user_watches
    state: present
    value: 52428
    sysctl_set: yes

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add me to the docker group
  user:
    name: audun
    groups: docker
    append: yes
    state: present

- name: Create directory for Docker
  file:
    path: /docker/data
    state: directory

- name: Setup Docker to use new directory
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: "^OPTIONS="
    line: "OPTIONS='--selinux-enabled -g /docker/data -p /var/run/docker.pid --log-driver=journald'"
  notify: Restart Docker Daemon
